In [1]:
import os
import pandas as pd

# Define the folder paths
base_path = r"C:/Users/tulio/Downloads/wisdm+smartphone+and+smartwatch+activity+and+biometrics+dataset/wisdm-dataset/wisdm-dataset/raw/watch"
gyro_folder = os.path.join(base_path, "gyro")
accel_folder = os.path.join(base_path, "accel")

In [2]:
# Function to read and concatenate all files in a folder
def read_sensor_data(folder_path, columns):
    all_files = [os.path.join(folder_path, f) for f in os.listdir(folder_path) if f.endswith(".txt")]
    dataframes = []

    for file in all_files:
        df = pd.read_csv(file, header=None, names=columns)
        dataframes.append(df)

    return pd.concat(dataframes, ignore_index=True)

In [3]:
# Read data from both folders
gyro_columns = ["Subject-id", "Activity Label", "Timestamp", "gyro_x", "gyro_y", "gyro_z"]
accel_columns = ["Subject-id", "Activity Label", "Timestamp", "acc_x", "acc_y", "acc_z"]

In [4]:
gyro_data = read_sensor_data(gyro_folder, gyro_columns)
accel_data = read_sensor_data(accel_folder, accel_columns)

In [5]:
# Merge the two DataFrames on the Timestamp column
merged_data = pd.merge(gyro_data, accel_data, on="Timestamp", suffixes=("_gyro", "_accel"))

In [6]:
# Display the first few rows of the merged DataFrame
merged_data.head()

,Subject-id_gyro,Activity Label_gyro,Timestamp,gyro_x,gyro_y,gyro_z,Subject-id_accel,Activity Label_accel,acc_x,acc_y,acc_z
0,1600,A,90426757696641,0.314944,-1.022277,-0.3099616;,1600,A,4.972757,-0.158317,6.6967316;
1,1600,A,90426807196641,0.387382,-0.618541,-0.048971802;,1600,A,3.253720,-0.191835,6.107758;
2,1600,A,90426856696641,0.070999,-0.209480,-0.1959783;,1600,A,2.801216,-0.155922,5.997625;
3,1600,A,90426906196641,0.037975,0.254976,-0.1565635;,1600,A,3.770868,-1.051354,7.731027;
4,1600,A,90426955696641,0.073129,0.719431,-0.0010349044;,1600,A,4.661511,0.169689,9.684695;

In [7]:
merged_data.drop(columns=["Subject-id_accel", "Activity Label_accel"], inplace=True)
merged_data.head()

,Subject-id_gyro,Activity Label_gyro,Timestamp,gyro_x,gyro_y,gyro_z,acc_x,acc_y,acc_z
0,1600,A,90426757696641,0.314944,-1.022277,-0.3099616;,4.972757,-0.158317,6.6967316;
1,1600,A,90426807196641,0.387382,-0.618541,-0.048971802;,3.253720,-0.191835,6.107758;
2,1600,A,90426856696641,0.070999,-0.209480,-0.1959783;,2.801216,-0.155922,5.997625;
3,1600,A,90426906196641,0.037975,0.254976,-0.1565635;,3.770868,-1.051354,7.731027;
4,1600,A,90426955696641,0.073129,0.719431,-0.0010349044;,4.661511,0.169689,9.684695;

In [10]:
merged_data.columns = ["user_id", "activity", "timestamp", "gyro_x", "gyro_y", "gyro_z", "acc_x", "acc_y", "acc_z"]

In [11]:
merged_data.head()

,user_id,activity,timestamp,gyro_x,gyro_y,gyro_z,acc_x,acc_y,acc_z
0,1600,A,90426757696641,0.314944,-1.022277,-0.3099616;,4.972757,-0.158317,6.6967316;
1,1600,A,90426807196641,0.387382,-0.618541,-0.048971802;,3.253720,-0.191835,6.107758;
2,1600,A,90426856696641,0.070999,-0.209480,-0.1959783;,2.801216,-0.155922,5.997625;
3,1600,A,90426906196641,0.037975,0.254976,-0.1565635;,3.770868,-1.051354,7.731027;
4,1600,A,90426955696641,0.073129,0.719431,-0.0010349044;,4.661511,0.169689,9.684695;

In [13]:
# Map activity labels to new values
activity_map = {
    "A": "Walking",
    "B": "Jogging",
    "C": "Stairs",
    "D": "Sitting",
    "E": "Standing"
}

merged_data["activity"] = merged_data["activity"].map(activity_map)

In [15]:
merged_data

,user_id,activity,timestamp,gyro_x,gyro_y,gyro_z,acc_x,acc_y,acc_z
0,1600,Walking,90426757696641,0.314944,-1.022277,-0.3099616;,4.972757,-0.158317,6.6967316;
1,1600,Walking,90426807196641,0.387382,-0.618541,-0.048971802;,3.253720,-0.191835,6.107758;
2,1600,Walking,90426856696641,0.070999,-0.209480,-0.1959783;,2.801216,-0.155922,5.997625;
3,1600,Walking,90426906196641,0.037975,0.254976,-0.1565635;,3.770868,-1.051354,7.731027;
4,1600,Walking,90426955696641,0.073129,0.719431,-0.0010349044;,4.661511,0.169689,9.684695;
...,...,...,...,...,...,...,...,...,...
3370856,1650,NaN,2426184371437252,-2.856065,2.057101,0.85393304;,2.137723,-7.211485,8.065467;
3370857,1650,NaN,2426184421424592,-2.911458,1.817417,1.2811041;,1.486500,-13.302334,5.355231;
3370858,1650,NaN,2426184471411932,-3.015854,1.550036,2.0576818;,4.017171,-13.146711,5.1182046;
3370859,1650,NaN,2426184521399272,-3.218254,1.595842,3.0185504;,4.412214,-15.318253,3.3704374;
3370860,1650,NaN,2426184571385262,-2.455525,0.866136,3.3541086;,4.426579,-13.012636,2.5755625;

In [16]:
# Drop rows with Activity Label not in the map
merged_data = merged_data.dropna()
merged_data

,user_id,activity,timestamp,gyro_x,gyro_y,gyro_z,acc_x,acc_y,acc_z
0,1600,Walking,90426757696641,0.314944,-1.022277,-0.3099616;,4.972757,-0.158317,6.6967316;
1,1600,Walking,90426807196641,0.387382,-0.618541,-0.048971802;,3.253720,-0.191835,6.107758;
2,1600,Walking,90426856696641,0.070999,-0.209480,-0.1959783;,2.801216,-0.155922,5.997625;
3,1600,Walking,90426906196641,0.037975,0.254976,-0.1565635;,3.770868,-1.051354,7.731027;
4,1600,Walking,90426955696641,0.073129,0.719431,-0.0010349044;,4.661511,0.169689,9.684695;
...,...,...,...,...,...,...,...,...,...
3324061,1650,Standing,2425530011432855,-0.248304,-0.548543,-0.22623792;,2.357989,-1.719186,10.213066;
3324062,1650,Standing,2425530061425505,-0.268544,-0.394079,-0.18149683;,2.487276,-1.676091,10.12448;
3324063,1650,Standing,2425530111418155,-0.255761,-0.246007,-0.19960631;,2.851195,-1.702427,9.988011;
3324064,1650,Standing,2425530161410805,-0.322873,-0.096870,-0.23582532;,2.884714,-1.611447,9.664794;
3324065,1650,Standing,2425530211403455,-0.340982,-0.007388,-0.22836846;,2.827253,-1.769465,9.284116;

In [17]:
# Save the merged DataFrame to a CSV file (optional)
output_path = os.path.join(base_path, "merged_data.csv")
merged_data.to_csv(output_path, index=False)