In [1]:
import os
import pandas as pd
from sklearn.utils import resample

In [2]:
# Define the folder paths
base_path = "C:/Users/tulio/Downloads/wisdm+smartphone+and+smartwatch+activity+and+biometrics+dataset/wisdm-dataset/wisdm-dataset/raw/watch"
gyro_folder = os.path.join(base_path, "gyro")
accel_folder = os.path.join(base_path, "accel")

In [3]:
# Function to read and concatenate all files in a folder
def read_sensor_data(folder_path, columns):
    all_files = [os.path.join(folder_path, f) for f in os.listdir(folder_path) if f.endswith(".txt")]
    dataframes = []

    for file in all_files:
        df = pd.read_csv(file, header=None, names=columns)
        dataframes.append(df)

    return pd.concat(dataframes, ignore_index=True)

In [4]:
# Read data from both folders
gyro_columns = ["Subject-id", "Activity Label", "Timestamp", "gyro_x", "gyro_y", "gyro_z"]
accel_columns = ["Subject-id", "Activity Label", "Timestamp", "acc_x", "acc_y", "acc_z"]

In [5]:
gyro_data = read_sensor_data(gyro_folder, gyro_columns)
accel_data = read_sensor_data(accel_folder, accel_columns)

In [6]:
# Merge the two DataFrames on the Timestamp column
merged_data = pd.merge(gyro_data, accel_data, on="Timestamp", suffixes=("_gyro", "_accel"))

In [7]:
# Display the first few rows of the merged DataFrame
merged_data.head()

,Subject-id_gyro,Activity Label_gyro,Timestamp,gyro_x,gyro_y,gyro_z,Subject-id_accel,Activity Label_accel,acc_x,acc_y,acc_z
0,1600,A,90426757696641,0.314944,-1.022277,-0.3099616;,1600,A,4.972757,-0.158317,6.6967316;
1,1600,A,90426807196641,0.387382,-0.618541,-0.048971802;,1600,A,3.253720,-0.191835,6.107758;
2,1600,A,90426856696641,0.070999,-0.209480,-0.1959783;,1600,A,2.801216,-0.155922,5.997625;
3,1600,A,90426906196641,0.037975,0.254976,-0.1565635;,1600,A,3.770868,-1.051354,7.731027;
4,1600,A,90426955696641,0.073129,0.719431,-0.0010349044;,1600,A,4.661511,0.169689,9.684695;

In [8]:
merged_data.drop(columns=["Subject-id_accel", "Activity Label_accel"], inplace=True)
merged_data.head()

,Subject-id_gyro,Activity Label_gyro,Timestamp,gyro_x,gyro_y,gyro_z,acc_x,acc_y,acc_z
0,1600,A,90426757696641,0.314944,-1.022277,-0.3099616;,4.972757,-0.158317,6.6967316;
1,1600,A,90426807196641,0.387382,-0.618541,-0.048971802;,3.253720,-0.191835,6.107758;
2,1600,A,90426856696641,0.070999,-0.209480,-0.1959783;,2.801216,-0.155922,5.997625;
3,1600,A,90426906196641,0.037975,0.254976,-0.1565635;,3.770868,-1.051354,7.731027;
4,1600,A,90426955696641,0.073129,0.719431,-0.0010349044;,4.661511,0.169689,9.684695;

In [9]:
merged_data.columns = ["user_id", "activity", "timestamp", "gyro_x", "gyro_y", "gyro_z", "acc_x", "acc_y", "acc_z"]

In [10]:
merged_data.head()

,user_id,activity,timestamp,gyro_x,gyro_y,gyro_z,acc_x,acc_y,acc_z
0,1600,A,90426757696641,0.314944,-1.022277,-0.3099616;,4.972757,-0.158317,6.6967316;
1,1600,A,90426807196641,0.387382,-0.618541,-0.048971802;,3.253720,-0.191835,6.107758;
2,1600,A,90426856696641,0.070999,-0.209480,-0.1959783;,2.801216,-0.155922,5.997625;
3,1600,A,90426906196641,0.037975,0.254976,-0.1565635;,3.770868,-1.051354,7.731027;
4,1600,A,90426955696641,0.073129,0.719431,-0.0010349044;,4.661511,0.169689,9.684695;

In [11]:
# Map activity labels to new values
activity_map = {
    "A": "Walking",
    "B": "Jogging",
    "C": "Stairs",
    "D": "Sitting",
    "E": "Standing"
}

merged_data["activity"] = merged_data["activity"].map(activity_map)

merged_data['gyro_z'] = merged_data['gyro_z'].astype(str).str.replace(';', '', regex=False)
merged_data['acc_z'] = merged_data['acc_z'].astype(str).str.replace(';', '', regex=False)

In [12]:
merged_data = merged_data.astype({
    'user_id': 'int32',              # Convert 'user_id' to integer
    'activity': 'string',            # Convert 'activity' to string
    'timestamp': 'int64',            # Convert 'timestamp' to integer
    'gyro_x': 'float32',             # Convert 'gyro_x' to float
    'gyro_y': 'float32',             # Convert 'gyro_y' to float
    'gyro_z': 'float32',             # Convert 'gyro_z' to float
    'acc_x': 'float32',              # Convert 'acc_x' to float
    'acc_y': 'float32',              # Convert 'acc_y' to float
    'acc_z': 'float32'               # Convert 'acc_z' to float
})
merged_data

,user_id,activity,timestamp,gyro_x,gyro_y,gyro_z,acc_x,acc_y,acc_z
0,1600,Walking,90426757696641,0.314944,-1.022277,-0.309962,4.972757,-0.158317,6.696732
1,1600,Walking,90426807196641,0.387382,-0.618541,-0.048972,3.253720,-0.191835,6.107758
2,1600,Walking,90426856696641,0.070999,-0.209480,-0.195978,2.801216,-0.155922,5.997625
3,1600,Walking,90426906196641,0.037975,0.254976,-0.156564,3.770868,-1.051354,7.731027
4,1600,Walking,90426955696641,0.073129,0.719431,-0.001035,4.661511,0.169689,9.684695
...,...,...,...,...,...,...,...,...,...
3370856,1650,<NA>,2426184371437252,-2.856065,2.057101,0.853933,2.137723,-7.211485,8.065467
3370857,1650,<NA>,2426184421424592,-2.911458,1.817417,1.281104,1.486500,-13.302334,5.355231
3370858,1650,<NA>,2426184471411932,-3.015854,1.550036,2.057682,4.017171,-13.146711,5.118205
3370859,1650,<NA>,2426184521399272,-3.218254,1.595842,3.018550,4.412214,-15.318253,3.370437
3370860,1650,<NA>,2426184571385262,-2.455525,0.866136,3.354109,4.426579,-13.012636,2.575562

In [13]:
# Drop rows with Activity Label not in the map
merged_data = merged_data.dropna()
merged_data['user_id'] = merged_data['user_id'] - 1599
merged_data

C:\Users\tulio\AppData\Local\Temp\ipykernel_20904\3705983176.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_data['user_id'] = merged_data['user_id'] - 1599

,user_id,activity,timestamp,gyro_x,gyro_y,gyro_z,acc_x,acc_y,acc_z
0,1,Walking,90426757696641,0.314944,-1.022277,-0.309962,4.972757,-0.158317,6.696732
1,1,Walking,90426807196641,0.387382,-0.618541,-0.048972,3.253720,-0.191835,6.107758
2,1,Walking,90426856696641,0.070999,-0.209480,-0.195978,2.801216,-0.155922,5.997625
3,1,Walking,90426906196641,0.037975,0.254976,-0.156564,3.770868,-1.051354,7.731027
4,1,Walking,90426955696641,0.073129,0.719431,-0.001035,4.661511,0.169689,9.684695
...,...,...,...,...,...,...,...,...,...
3324061,51,Standing,2425530011432855,-0.248304,-0.548542,-0.226238,2.357989,-1.719186,10.213066
3324062,51,Standing,2425530061425505,-0.268544,-0.394079,-0.181497,2.487276,-1.676091,10.124480
3324063,51,Standing,2425530111418155,-0.255761,-0.246007,-0.199606,2.851195,-1.702427,9.988011
3324064,51,Standing,2425530161410805,-0.322873,-0.096870,-0.235825,2.884714,-1.611447,9.664794
3324065,51,Standing,2425530211403455,-0.340982,-0.007388,-0.228368,2.827253,-1.769465,9.284116

In [14]:
# Function to balance the dataset
def balance_dataset(df, class_column):
    # Count the occurrences of each class
    class_counts = df[class_column].value_counts()
    min_count = class_counts.min()

    print(min_count)

    # Resample each class to have the same number of occurrences as the class with the smallest count
    balanced_df = pd.DataFrame()
    for activity in class_counts.index:
        activity_df = df[df[class_column] == activity]
        resampled_df = resample(activity_df, replace=False, n_samples=min_count, random_state=42)
        balanced_df = pd.concat([balanced_df, resampled_df], ignore_index=True)
    
    return balanced_df

# Balance the dataset
balanced_df = balance_dataset(merged_data, "activity")

181618

In [16]:
merged_data['activity'].value_counts()

activity
Standing    195324
Sitting     192594
Walking     186149
Stairs      183264
Jogging     181618
Name: count, dtype: Int64

In [15]:
balanced_df

,user_id,activity,timestamp,gyro_x,gyro_y,gyro_z,acc_x,acc_y,acc_z
0,23,Standing,202361635538231,0.097854,-0.072027,0.037987,-9.501988,2.196381,1.655740
1,20,Standing,349612597304847,-0.002166,-0.026851,0.016018,8.908675,-3.222745,-2.205509
2,9,Standing,718351244889960,-1.562171,-1.008306,-0.313409,10.693851,-2.672677,2.562993
3,16,Standing,78403713292521,-0.012419,-0.003924,0.011186,9.108142,-3.257162,1.729511
4,24,Standing,8675267032180,-0.017867,0.009935,0.003913,9.354445,-2.619556,-0.048931
...,...,...,...,...,...,...,...,...,...
908085,32,Jogging,1328334874979359,1.075169,-0.350914,4.339064,0.537049,-17.506552,-0.216526
908086,30,Jogging,901585516925509,-0.117404,2.080966,1.328017,-15.049802,-0.518644,-0.627131
908087,35,Jogging,83792601860550,1.273759,-2.020176,3.352290,6.398654,-9.371354,3.377171
908088,42,Jogging,1219665222464572,0.997640,-1.978410,2.709746,4.959439,-2.623147,-2.760814
908089,32,Jogging,1328438651083199,-2.314260,2.350556,-1.738039,-5.297620,-19.354876,0.702848

In [19]:
# Save the merged DataFrame to a CSV file (optional)
output_path = os.path.join(base_path, "WISDM_complete_preprocessed.csv")
merged_data.to_csv(output_path, index=False)